name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install JDK 11
        uses: actions/setup-java@v3
        # jdk 11버젼을 쓰기위한 세팅
        with:
          java-version: '11'
          distribution: 'temurin'
        # clean 타겟 폴더 정리
        # -D 옵션 명령어를 사용할때 씀
      - name: Build SpringBoot Server
        # 형식 chmod 사용자번호, 그룹번호 , 외부의 번호  권한을 주고싶은 파일
        run: |
          chmod 700 ./mvnw 
          ./mvnw clean package -Dtestskip
          
      - name: show Directory
        run: |
          ls -a
          cd ./target
          ls -a
